spring:
  redis:
    port: 6379
    host: 127.0.0.1
    password: redis
  datasource:
    url: jdbc:h2:mem:distributed-lock;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: user
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
